spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airlines_ticket_reservation_v2
    username: root
    password: pass
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: airlines_tickets_reservation

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG